### ISSUE TITLE
How to fix http assets call?

### ISSUE THREAD

**Issue by TheZoker** [devaslanphp/project-management#51]
Hi there,

I'm trying out the new docker image and use a reverse proxy to access my helper instance. 
The issue now is, that the assets do not seem to be loaded via https but via http, which causes issues:
![image](https://user-images.githubusercontent.com/1368405/214172817-7b43648b-20b0-4ab9-bb37-b508508bce38.png)

I already set the `APP_URL` to match my https url, but that did not change anything. 

Would really appriciate some hints :)

Thanks!

**Comment by heloufir** [comment]
Hello @TheZoker 

Did you try to force using `https` instead of `http` in your `AppServiceProvider`?

You can add this to your `AppServiceProvider`:

```php
// ...
public function boot()
{
        if ($this->app->environment('production')) { // Force using https if the APP_ENV equals to "production"
            \Illuminate\Support\Facades\URL::forceScheme('https');
        }
        // ...
}
// ...
```

You can change the condition as you need.

**Comment by TheZoker** [comment]
Hi @heloufir,

I'm using the hub image. I added the `\Illuminate\Support\Facades\URL::forceScheme('https');` directly into the `AppServiceProvider` file (without any conditional wrapper), but it does not seem to change anything.

**Comment by heloufir** [comment]
@TheZoker 
I think you can use the `ASSET_URL` environment variable in your `docker-compose.yml` file, like below:

```yml
...
  helper:
    image: eloufirhatim/helper:latest
    container_name: ...
    environment:
      - ...
      - ASSET_URL=https://your_domain.com
...
```

I just made the same test in my local and here is the results:

![image](https://user-images.githubusercontent.com/6197875/214303886-2517896e-cdf6-469a-a7af-e129ecf5531a.png)

**Comment by TheZoker** [comment]
That seems to help a little.
When I access the page on my local network without HTTPS, the `filament.*.js` get loaded via the `ASSET_URL`, but `/filament/assets/filament-icon-picker-styles.css`, `/filament/assets/app.js` and `/filament/assets/echo.js` get loaded via HTTP.

**Comment by heloufir** [comment]
Hmm, the first file `filament.*.js` is managed by the `helper` application (this repo), but the others are used inside packages that this repo depends on: 
- `/filament/assets/filament-icon-picker-styles.css`: `guava/filament-icon-picker` package
- `/filament/assets/app.js` and `/filament/assets/echo.js`: `filament/filament` package

I will check if there is something to configure to let this work and let you know!

**Comment by TheZoker** [comment]
Thanks!

Good question, whatever the docker container is using as a web server:
https://github.com/devaslanphp/project-management/blob/master/Dockerfile#L4

**Comment by heloufir** [comment]
In nginx for example, you can add a permanent redirect from HTTP to HTTPS, like below:

```
server {
    listen 80;
    server_name youdomain.com;

    return 301 https://youdomain.com$request_uri;
}


server {
    listen 443 ssl http2;
    server_name youdomain.com;
...
}
```

**Comment by heloufir** [comment]
> In nginx for example, you can add a permanent redirect from HTTP to HTTPS, like below:
> 
> ```
> server {
>     listen 80;
>     server_name youdomain.com;
> 
>     return 301 https://youdomain.com$request_uri;
> }
> 
> 
> server {
>     listen 443 ssl http2;
>     server_name youdomain.com;
> ...
> }
> ```
> 
> More details: https://robindirksen.com/blog/laravel-redirect-to-https-a-middleware-to-force-https#force-https-with-nginx

@TheZoker 
Did you test the nginx conf example above?

**Comment by TheZoker** [comment]
I'm using NGNX Proxy manager to handle the request:
https://nginxproxymanager.com/

I'm not sure how to set this up there. But I think the web app should load the schema correctly.
If I set the assets url, the assets should be loaded via this URL right?

**Comment by heloufir** [comment]
@TheZoker 
Yep, normally the application should load URLs right, I just wanted to know if using the Nginx configuration will change anything.

Anyway, I'm looking for a solution.
I will let you know ASAP if I find a solution.

**Comment by heloufir** [comment]
I think in addition to the env variable `ASSET_URL=https://your_domain.com` you will need to add the Nginx server block I have said in my previous command.

So I think you are using the Nginx Proxy Manager Docker image, you can use the terminal of your docker image, to access the volume of your container and then search the nginx configuration file and add the following block, to redirect HTTP to HTTPS : 

```
server {
    listen 80;
    server_name youdomain.com;

    return 301 https://youdomain.com$request_uri;
}
```

I've never used this tool before, but using Nginx or Apache, I always add a redirection to HTTPS in my host

**Comment by TheZoker** [comment]
Hmm I think these custom nginx configurations would then apply to all entries in the manager not just this one. 

Within a entry there is this option, which I enabled right at the beginning:
![image](https://user-images.githubusercontent.com/1368405/214842520-0b360aab-c80b-4128-a72d-42a2448aedff.png)

This redirects the calls to https and for all other 25+ applications this works without issue, but not for helper for some reason 🤔

**Comment by heloufir** [comment]
I will need to reproduce this in my environment to check what can cause this, I will let you know after that.

**Comment by TheZoker** [comment]
Thanks :)

Here is my `compose` file:
```
version: '3.8'
services:
  helper:
    image: eloufirhatim/helper
    container_name: Helper
    restart: always
    ports:
      - 80:8000/tcp
    environment:
      - APP_URL=<secret>
      - ASSET_URL=<secret>
      - APP_NAME="Projects"
      - DB_CONNECTION=mysql
      - DB_HOST=<secret>
      - DB_PORT=3306
      - DB_DATABASE=<secret>
      - DB_USERNAME=<secret>
      - DB_PASSWORD=<secret>
      - MAIL_MAILER=smtp
      - MAIL_HOST=<secret>
      - MAIL_PORT=587
      - MAIL_USERNAME=<secret>
      - MAIL_PASSWORD=<secret>
      - MAIL_ENCRYPTION=tls
```

I replaced all the sensitive information with `<secret>`. Let me know if you need anything else. And thanks for taking the time to debug this with me :)
